dist: xenial
language: java
jdk:
- openjdk8
before_install:
- openssl aes-256-cbc -K $encrypted_77f17bf3ee01_key -iv $encrypted_77f17bf3ee01_iv -in fake-creditcard.gpg.enc -out fake-creditcard.gpg -d
install: "./gradlew assemble -x signArchives"
script:
  - ./gradlew check
after_success:
- ./gradlew uploadArchives -PnexusUsername="${SONATYPE_USERNAME}" -PnexusPassword="${SONATYPE_PASSWORD} -Psigning.keyId=${GPG_KEY_ID} -Psigning.password=${GPG_KEY_PASSPHRASE} -Psigning.secretKeyRingFile=fake-creditcard.gpg"
env:
  global:
    - COVERALLS_REPO_TOKEN=${REPO_TOKEN}