dist: xenial
language: java
jdk:
- openjdk8
script: ./gradlew clean build
after_success:
- ./gradlew uploadArchives -PnexusUsername="${SONATYPE_USERNAME}" -PnexusPassword="${SONATYPE_PASSWORD}"
env:
  global:
    - COVERALLS_REPO_TOKEN=${REPO_TOKEN}