dist: xenial
language: java
jdk:
- openjdk8
install: "./gradlew assemble -x signArchives"
script:
  - ./gradlew check
after_success:
- ./gradlew uploadArchives \
    -PnexusUsername="${SONATYPE_USERNAME}" \
    -PnexusPassword="${SONATYPE_PASSWORD} \
    -Psigning.keyId=${GPG_KEY_ID} \
    -Psigning.password=${GPG_KEY_PASSPHRASE} \
    -Psigning.secretKeyRingFile=fake-creditcard.gpg"
env:
  global:
    - COVERALLS_REPO_TOKEN=${REPO_TOKEN}