dist: xenial
env:
  global:
    - COVERALLS_REPO_TOKEN=${REPO_TOKEN}
    - GPG_KEY_LOCATION="fake-creditcard.gpg"
    - ENCRYPTED_GPG_KEY_LOCATION="fake-creditcard.gpg.enc"
    - secure: SONATYPE_USERNAME
    - secure: SONATYPE_PASSWORD
    - secure: GPG_KEY_ID
    - secure: GPG_KEY_PASSPHRASE
branches:
  only:
  - master
language: java
jdk:
  - openjdk8
before_script: cd project
before_install:
  - chmod -R ug+x .travis
  - .travis/install.sh