dist: xenial
env:
  global:
  - COVERALLS_REPO_TOKEN=${REPO_TOKEN}
  - secure: fJNYQPd4725bWGjCF+md8OpcX7y+XAmul/bMf8O1uUSDxN33Dya7t9IiV/ned5jX93durm1AxbIr6aSnhR6MzNUxj3zLmwI0BsDzjhSe/gFBAMJqWEvof9qaa6Yv/Zhda6SRecPfY2No1j4+1uajoY/By+ln/qZoTmCfSiA1N/FTN4eEvVQp6xtMgyLawuefQ9N7I2wND4HkWbNanx/k9EuMgNk/nKLWuXqG3d1Gxo5hvtvh5zzOu2jMWSQNIBVT6m6KgXPTolkUtdevgb36/WX+Emc7ut9RIbKvfXtVnO0onr70NfCaAGJo3zcXgjiaK/K5YybnFuAt7C91Us7BO5pHG1NtYfwL2TYPjF53KDQiIRMNTusDvdyiZg4xEEwM1zd0mHcFJUHk4noVBCG0yiPVyPAzzUpeukC1xhFxE+iXI7CdTZcgslf/nbiGWSE4o7XWO1MPzm1y4baYb3DYTYYH0VtBUZ5xWOFH2klg9ploPUrYPwjofzouVwexIayEBH6FOm6DlZyqRXZI4IiTcDZmG+kimxUIrViRaNYNzjUpgrMJw5SZ2I8I/yhWLwslNXh94KrYWQx0CKKcovcGJJMyHT49eVQFpmEyD9KMfWuZHe3Joozu434qKatVeSMyLy1yrqmdx41SnRpKkwf91FJ6ZI3cyIGw47mdvvc84yM=
  - secure: FON3Aaj1739EfluTPQjZdvNeX31WwtPZE3yrw9Wzlxn8CsUbQ4EfXHvsXQeOUejz9eLF2eaWjKGCLBBQRv2d81g7+AB1o3uF0g02GSBB0SYsxWKrVaOfseFteSfFy+I9B6AT0IZ6tnHewJlifumkKSWTrIwP3btPQC1/yJG6mNsvOvna94sQOa+j3J8HAPQL2gIcQO4CSegHaKm52L4T3c38Yxr1ilDsS1CGkuTc80DluRK0ZBiljIMEtmrpy3bHCXWibbmy3lHMaYR3UGK51aczfxyCi0UnisK9XCOooQ3vSl4hmGaDmrG7nYYu3wE4Xzg5nQqZpyvD0gWhdIWMdM8QMcikGJPTZKYo8exdugpgb+QwTHJYc0fmyJ1H/EJLBvAO8J3ud/CdZXVEbCpA1Dju76smNeyIijFtRUGx3jxh9geYAEfE5uQouowjpDluOyi95zf1VecWapxNEbrntE5NXiVZbemrbBiUFrLWEFUcEY6nlzyjxOrc0SYpiNe5TocJktIif1FymTt/N4+kKLZc/7CUkRZCgFIzMO9J8U8UgjlsSEplYdl5WR+O7oaEdSwiL08NDK/tWhLA+kb/C87RpfXICzYuRUbXwlWt4P35piPe1zOPVn5LI7sl9IhK4k0oVxlEqmJqi7ZfgnhgnKC6eVrb9Hmq5Czn3BphbCM=
language: java
jdk:
- openjdk8
install:
- chmod -R ug+x .travis
- ".travis/build.sh"
after_success:
- chmod -R ug+x .travis
- ".travis/deploy.sh"
#- ".travis/release.sh"

